### ISSUE TITLE
部落格的文章都消失了

### ISSUE THREAD

**Issue by dryden** [oniondelta/Onion_Rime_Files#1]
今天要輸入簡體時突然忘記快速鍵怎麽按，才發現部落格關於中文輸入的文章都消失了，發生了什麼事情嗎？
感謝您修改出這麼好用的版本

**Comment by oniondelta** [comment]
「GitHub」和「部落格」兩邊都更新太累了！
那邊容易吸引一些OOXX的人，搞得煩心！
後期也沒抖內等開心因素，故沒啥動力兩邊搞！
