### ISSUE TITLE
在ubuntu 18.04 底下，打中文預設會出英文 但是如果有選字就會出中文??

### ISSUE THREAD

**Issue by changchichung** [oniondelta/Onion_Rime_Files#10]
這問題有點奇怪

我是從 ubuntu 20.04 上面 把 ~/.config/fcitx/rime 整個打包上面，轉到 18.04 的機器上
然後解開到對應的目錄，重新佈署，佈署的過程沒有錯誤
上個 GIF 看看會不會比較容易了解
![](https://i.imgur.com/BoZKdZi.gif)

GIF 一開始我打中文，但是不選字，直接按enter 出字，都會是英文
可是到結束的時候，我用ctrl+2 去選第二順序的字，就可以正常出中文

在 ubuntu 20.04 上面沒有這個問題
請問如果我要在18.04 的機器上調整設定的話，應該要看哪個選項？

update: 
不管選哪個方案都是一樣的狀況，至少我用了 bo_mixin1 和純注音版 都是這樣

**Comment by oniondelta** [comment]
ubuntu 不熟！也沒機器測試！
1. 你開頭選項怎麼會是 1234，這邊設定是 QAZWSX 的，有修改？或是 fcitx 的原因？
2. 只在 Win 和 Mac 遊移，發現過 Mac 可行的設定程式碼，在 Win 會造成軟體死當， fcitx 應該也會有這類兼容問題！
3. 發現你的 lua 無法作用（〔雷布查語標點〕不應該出現，會被 lua 功能遮屏）！rime.lua 屬於外掛的設定檔，裡面這邊寫了一堆功能。雖是外掛， Mac 或 Win 官方封裝都有附該外掛，不知道 fcitx 的情形，fcitx 不屬於 Rime 官方維護的。改成用 ibus-rime？

**Comment by oniondelta** [comment]
ubuntu 不熟！也沒機器測試！
1. 你開頭選項怎麼會是 1234，這邊設定是 QAZWSX 的，有修改？或是 fcitx 的原因？
2. 只在 Win 和 Mac 遊移，發現過 Mac 可行的設定程式碼，在 Win 會造成軟體死當， fcitx 應該也會有這類兼容問題！
3. 發現你的 lua 無法作用（〔雷布查語標點〕不應該出現，會被 lua 功能遮屏）！rime.lua 屬於外掛的設定檔，裡面這邊寫了一堆功能。雖是外掛， Mac 或 Win 官方封裝都有附該外掛，不知道 fcitx 的情形，fcitx 不屬於 Rime 官方維護的。改成用 ibus-rime？
4. 建議官方注音方案也測一下！

update:

- 爬文一下，發現 fcitx-rime 發佈修改日期好似很久前？推測沒支援 lua 功能？如果是不建議使用 mix-in 版！
- fcitx-rime 更新版本超舊的？應該用舊的 rime 核心？如果是不太推薦！
 https://github.com/fcitx/fcitx-rime
 https://github.com/fcitx/fcitx-rime/tags
 https://github.com/rime/home/issues/626
 https://github.com/hchunhui/librime-lua/issues/24

- 看更新日期 fcitx5-rime 或許有機會支援 lua？
https://github.com/fcitx/fcitx5-rime
https://github.com/fcitx/fcitx5-rime/issues/29

- 試試官方 ibus-rime？
https://github.com/rime/ibus-rime

**Comment by changchichung** [comment]
感覺在18.04 底下好多問題

什麼也沒改動的情況下，只是多次開啟/關閉 fcitx 
就會出現有時候可以打中文 有時候不能打中文的問題
有時候可以打符號〔頓號〕 有時候符號又出不來...

18.04 也裝不了 fcitx5，看來是沒救了

**Comment by oniondelta** [comment]
https://github.com/hchunhui/ibus-rime.AppImage

**Comment by changchichung** [comment]
ibus 我用起來問題多多，更何況打包之後的..
我還是學著怎麼自己做多國語言混打好了..

如果要從頭開始自己刻，有什麼好建議嗎？
