### ISSUE TITLE
在某些程式中 輸入法的行為變得很奇怪

### ISSUE THREAD

**Issue by changchichung** [oniondelta/Onion_Rime_Files#18]
環境： ubuntu 22.04 + fcitx5-rime
安裝方式依照說明，git clone 之後，去跑 sort_time_file.py 然後將產生出來的檔案 複製到 ~/.local/share/fcitx5/rime/ 底下
在某些程式中 輸入法不會正常的上字

請參考影片內容
https://youtu.be/mmnCLjqPAtI

測試過了兩三台機器，都是一樣的狀況，不曉得有什麼建議？

**Comment by oniondelta** [comment]
有測試過 Win 或 Mac 系統嗎？
看影片中 preedit 的格式，有被 \n 分行影響，這個 Win 也不吃
[分行說明](https://github.com/oniondelta/Onion_Rime_Files/wiki/%E3%80%8E-%E6%B3%A8%E9%9F%B3-%E6%B4%8B%E8%94%A5-mixin-%E7%89%88-%E3%80%8F%E6%96%B9%E6%A1%88%E8%AA%AA%E6%98%8E#-%E6%B3%A8%E9%9F%B3%E5%92%8C%E8%8B%B1%E6%96%87%E7%B7%A8%E7%A2%BC%E5%90%8C%E9%A1%AF)
建議先如同 Win 加 custom 檔

**Comment by oniondelta** [comment]
- 如果不吃方案內程式碼 style/inline_preedit: false， 勢必要取消勾選「顯示預編輯字串」！否則會有問題！

- 沒取消勾選還能正常，可能安裝套件後，可以接受到方案設定檔的該條指定（指定前端介面）

- 候選字必需為「垂直列表」，否則方向鍵選字等操作會有問題！「橫式列表」需另改設定！

- 最新版 Rime 核心 librime 可以做到兼容直式選單和橫式選單的設定，目前方案尚未如此設定。

- [Rime 入門需知](https://github.com/oniondelta/Onion_Rime_Files/wiki/Rime-%E5%85%A5%E9%96%80%E9%9C%80%E7%9F%A5)

### 目前想到的， fcitx5-rime 可能還有以下問題：

- [候選編號問題](https://github.com/fcitx/fcitx5-rime/issues/3)

- 前陣子方案內寫 lua 不想被侷限，不管 librime-lua 版本，非注音方案確定有用到最新版的函數，不知 mixin 是否也有踩到？！

### 以下看你方便，可否提供以下操作影片？

- 一般注音打字狀況。

- 打出「笑」該字，不要馬上上屏，欲看選單，測試 opencc 是否正常。

- 輸入「ㄏㄠˉ」該注音，不要馬上上屏，欲看選單，測試字符範圍功能是否正常。

- 「 ' 」「 / 」「 v 」 lua 寫的版本訊息。

- 「 ' 」「 / 」「 ; 」「 c 」「 a 」「 r 」可能踩到較新版 lua 函數（舊版會有問題）。

**Comment by oniondelta** [comment]
感謝回應反饋

- 選字編號沒有問題！新版 fcitx5-rime 有更新！👍🏻

- opencc 功能正常👍🏻

- 字符範圍正常 👍🏻

- librime-lua 版本太低，不過 mixin 目前想得到有疑慮的功能正常，其他方案或之後改寫，有可能會踩到新的 librime-lua 函數，造成不正常。

- 《easy》英漢字典的 comment 翻譯可以像 Mac 上一樣用 \n 分行，這在 Win 中會崩潰。👍🏻

### 建議

- preedit 雖然沒有 inline「顯示預編輯字串」，可正常，但推薦 [mixin注音_同顯1修改檔(Win)](https://github.com/oniondelta/Onion_Rime_Files/tree/main/allfiles/mixin%E6%B3%A8%E9%9F%B3_%E5%90%8C%E9%A1%AF1%E4%BF%AE%E6%94%B9%E6%AA%94(Win)) 或 [mixin注音_同顯2修改檔(Win)](https://github.com/oniondelta/Onion_Rime_Files/tree/main/allfiles/mixin%E6%B3%A8%E9%9F%B3_%E5%90%8C%E9%A1%AF2%E4%BF%AE%E6%94%B9%E6%AA%94(Win)) 擇其一加入（裡面的 custom 檔拉到rime資料夾下，『重新部署』）

- 其中 easy_en_lower.custom.yaml 不要加

- 其他 custom 檔，底下程式碼全部清除，這是不讓《easy》英漢字典的 comment 翻譯分行和太長，防 Win 崩潰用。
 
```yaml
  e_reverse_lookup/comment_format:
    # - xform/^.+⌗// #easy_en_super用
    # - xform|^[ a-z;/.'-]+|| #easy_en_super用
    # - xform/^(﹝.+﹞)?\[[^@]+\]/$1/
    - xform/^(﹙.+﹚)?\[[^[]+\]/$1/
    - xform/([a-zA-Z0-9])@([a-zA-Z0-9])/$1 $2/
    - xform/@@/ /
    - xform/@//
    # - xform/^([^﹝])/ $1/
    - xform/^([^﹙])/ $1/
    - xform/^((?:[\0-\x7F\xC2-\xFD][\x80-\xBF]*){30})(?:[\0-\x7F\xC2-\xFD][\x80-\xBF]*)+$/$1 ……《略》/
    # - xform/^(.{50}).+$/$1 ……《略》/  #會產生亂碼。
```
