### ISSUE TITLE
關於洋蔥plus版無法藉由「ctrl+=」實現部分軟體文字下標的功能

### ISSUE THREAD

**Issue by dyian456** [oniondelta/Onion_Rime_Files#19]
作者您好，想跟您詢問關於洋蔥plus版在如office、origin等軟體「ctrl+=」下標指令是無反應，而「ctrl+shift+=」上標指令則是能正常運作，然而在純注音版中兩個上下標指令則是都能正常執行。

在plus版中的文件中沒看到「ctrl+=」有拿來做功能鍵，想請問是否有辦法修改，謝謝您！

**Comment by oniondelta** [comment]
「ctrl」+「=」有拿來做功能鍵！為 comment 提示碼開關，

修改 element_bopomo.yaml 該檔
把`key_binder:` 下面該行「#」遮屏或刪除：
```yaml
    - {accept: Control+equal, toggle: back_mark, when: always }
```
