### ISSUE TITLE
有辦法減少重新部署時間嗎

### ISSUE THREAD

**Issue by p9989899898** [oniondelta/Onion_Rime_Files#2]
感謝弄了這麼好的輸入法
用了注音plus很順手，英文字典功能很實用
但是改了些快捷鍵要等重新部署準備完畢才能啟動

請問要如何關閉不常用的語言，關閉後能夠減少載入的部署時間嗎
看了一整個下午不是很能理解這些檔案怎麼串的

**Comment by oniondelta** [comment]
才摸一個下午🤨！


動到字典檔，部署時間會比較久
因要重建 bin 檔
動到 default.custom.yaml 該檔，如果裡面加載方案很多，部署也會比較久
default.custom.yaml 為全域性質，所有方案都會被影響！
單純修改「注音plus」快捷鍵
修改 element_bopomo.yaml 該檔，部署很快！
除非你把這邊其他注音方案也加進去，
一修改所有注音方案會一併修改，部署會慢一點


要關掉不常用語言自己研究吧😡😡😡
那可是花了好幾年的時間持續修改完成的！！！😡😡😡
你用不到，不代表別人不會用
掛載在那，也不影響一般使用！


注音plus：
- bopomo_onionplus.schema.yaml：
設定主檔
- element_bopomo.yaml
設定主檔會使用到元件一（key_binder 快捷鍵設定等，供設定主檔匯入）
- punct_bopomo.yaml
設定主檔會使用到元件二（標點符號鍵位，供設定主檔匯入）
========================
- bopomo_onionplus.extended.dict.yaml：
主字典（彙集以下字典，供設定主檔使用）
- terra_pinyin_onion.dict.yaml：
中文拼音字詞典（單字、詞彙）
- terra_pinyin_onion_add.dict.yaml：
中文拼音字典（非字典裡有的發音，主要補空碼和慣用發音）
- phrases.chtp.dict.yaml：
中文拼音字詞典（只有詞彙）


以上為注音plus的注音主架構，其他外語為掛載方案，太多了不寫了！

**Comment by oniondelta** [comment]
才摸一個下午🤨！


動到字典檔，部署時間會比較久
因要重建 bin 檔
動到 default.custom.yaml 該檔，如果裡面加載方案很多，部署也會比較久
default.custom.yaml 為全域性質，所有方案都會被影響！
單純修改「注音plus」快捷鍵
修改 element_bopomo.yaml 該檔，部署很快！
除非你把這邊其他注音方案也加進去，
一修改所有注音方案會一併修改，部署會慢一點
如果修改誤植錯誤代碼，某些情形不會報錯，但部署時間會較久！！！
要關掉不常用語言自己研究！
那可是花了好幾年的時間持續修改完成的！！！😡
要修改某些部分，尤其是字詞典，重型方案部署一定會較久
注音 plus 方案還不是部署最久的，也遇過其他人的重型方案，部署更久
這邊也是這樣過來的


注音plus：
- bopomo_onionplus.schema.yaml：
設定主檔
- element_bopomo.yaml
設定主檔會使用到元件一（key_binder 快捷鍵設定等，供設定主檔匯入）
- punct_bopomo.yaml
設定主檔會使用到元件二（標點符號鍵位，供設定主檔匯入）
========================
- bopomo_onionplus.extended.dict.yaml：
主字典（彙集以下字典，供設定主檔使用）
- terra_pinyin_onion.dict.yaml：
中文拼音字詞典（單字、詞彙）
- terra_pinyin_onion_add.dict.yaml：
中文拼音字典（非字典裡有的發音，主要補空碼和慣用發音）
- phrases.chtp.dict.yaml：
中文拼音字詞典（只有詞彙）


以上為注音plus的注音主架構，其他外語為掛載方案，太多了不寫了！
