### ISSUE TITLE
請問如何輸入雙引號？

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Onion_Rime_Files#21]
目前已知引號`「」`只要按下`［］`就可以打出來，但是雙引號該怎麼輸入呢？

**Comment by oniondelta** [comment]
https://github.com/oniondelta/Onion_Rime_Files/wiki/%E3%80%94%E6%B4%8B%E8%94%A5%E6%B3%A8%E9%9F%B3%E7%B3%BB%E5%88%97%E3%80%95%EF%BC%9A%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F
