### ISSUE TITLE
Plus Space方案 + Easy English 導致程式 Crash

### ISSUE THREAD

**Issue by zhtw2013** [oniondelta/Onion_Rime_Files#22]
系統：win11 最新版
洋蔥方案：20230420最新版

已將 Windows 需要的的三個檔案都放到使用者資料夾中了
在 Plus 一般方案能正常使用 Easy English

但切換到 Plus Space 方案
按啟始鍵數字3 啟動 Easy English
之後按鍵盤任一字元輸入文字都會導致程式 Crash

想請教有解決方法嗎？

**Comment by oniondelta** [comment]
要查一下，方案太多！沒每個方案在每個系統中一一細測！

**Comment by oniondelta** [comment]
查了一下發現
```
__patch:
```
不能和 `custom 檔` 合用
以致防崩潰的  `custom 檔` 無法作用

**Comment by zhtw2013** [comment]
> 查了一下發現 schema 中
> 
> ```
> __patch:
> ```
> 
> 不能和 `custom 檔` 合用 以致 Win 中防崩潰的 `custom 檔` 無法作用 這邊再看看怎麼改寫

感謝 辛苦惹！

**Comment by oniondelta** [comment]
修正上傳好了！
建議全部重新下載部屬！
請測試一下！
沒問題的話，也留言回報一下吧！

**Comment by zhtw2013** [comment]
> 修正上傳好了！ 建議全部重新下載部屬！ 請測試一下！ 沒問題的話，也留言回報一下吧！

可以了，感謝洋蔥大這麼快修復，我用綠界贊助洋蔥大喝杯咖啡！

**Comment by oniondelta** [comment]
感謝贊助！🎉
感謝回報 Bug！🙂
