### ISSUE TITLE
洋蔥MIX 無法切換繁簡

### ISSUE THREAD

**Issue by botio** [oniondelta/Onion_Rime_Files#23]
系統：win10 最新版
洋蔥方案：20230526

使用快捷鍵ctrl+; 切換到簡體之後 就不能切換回來了。

但是MAC正常，

想請教有解決方法嗎？

DEFAULT.custom.yaml 變動 已經更正

**Comment by botio** [comment]
default.custom.yaml 設置變動導致，已解決 

但是 CTRL + SHIFT + * 等等 的功能 都沒有效果

**Comment by oniondelta** [comment]
20230526 新修改下排快捷鍵切換為指定，切換回預設多 shift，欲循環切換用上排 control+shift+ 「1-9」。

修改時忽略 control+shift+「key」，其「key」Mac 和 Win 寫法不一樣，
已補正。

**Comment by botio** [comment]
剛剛發現  control+shift+ 「1-9」 要維護好幾次才會成功。。。不知道是不是跟WINDOWS 原本的 control+shift 功能衝突的關係，我個人已經改回原本的 ctrl+; 切換到繁簡 謝謝

**Comment by oniondelta** [comment]
更新要全部檔案都換！

`control+shift+ 「1-9」是 Rime 官方預設的切換！！！`

上條，20230526 版Win中可用碼被這邊遮屏！

一開始這邊 Mac 一切都正常！

要應付那麼多系統！累呀！

**Comment by botio** [comment]
辛苦了，感謝你的付出，覺得很感激。 已經用了很久，覺得很不錯的輸入法。

**Comment by oniondelta** [comment]
剛剛轉到 Win了10 測試所有方案快捷鍵，
以 20230526 這邊 GitHub 最新更新方案，
除了「行列30」和「形碼」方案 用到 control+shift+0，會失效，
快捷鍵皆可正常切換！！！

 control+shift+0 失效原因：https://dotblogs.com.tw/esyc2001/2013/05/23/104808
把 Win 系統中切換輸入法的快捷鍵改掉可避免，
這衝突在 Win 原生注音輸入法中同樣也發生😰，
control+shift+0 在 Win 系統注音預設可輸入標點『 」』，也因衝突無法！

另測試用「記事本」，於其他軟體內輸入，多少可能會快捷鍵衝突，
方案快捷鍵鍵位不管如何設置，皆無法避免！

**Comment by botio** [comment]
回報一個好消息： FEDORA 38 最新版本 安裝 RIME 以及 洋蔥注音 MIX 都能正常使用 沒有問題 。。。 只是建構維護的時間有點長 因為功能設定蠻多的XD 試了很多套LINUX 總算有一套可以穩定使用

**Comment by oniondelta** [comment]
LINUX 上 Rime 輸入法有三套： ibus-rime、fcitx-rime、fcitx5-rime
之前有人反餽，ubuntu 22.04 + fcitx5-rime 功能可正常，但需額外安裝套件！
ibus-rime 也可！前提也是需解決 librime-lua 外掛問題！

https://github.com/oniondelta/Onion_Rime_Files/wiki/Rime-%E5%85%A5%E9%96%80%E9%9C%80%E7%9F%A5

建構維護是指方案部屬嗎？
如果是，部屬時間要短，可用這邊純注音！mixin 主要是各語言字詞庫和轉寫很龐大，部屬時間自然長！
mixin 掛接的日語方案（前綴：4），單方案這邊老 Mac 部屬的時間就近五分鐘！

**Comment by botio** [comment]
ibus-rime (Fedora 38 目前安裝的版本） 
 
之前在各大LINUX DISTRO都有某些軟體無法正常打字的問題，所以乾脆就放棄使用，UBUNTU 22 版本確實也可以正常使用，但不太順暢，就是會LAG。

另 Win 小狼毫推薦用 [fxliang](https://github.com/fxliang/weasel/actions) 版 <<< 我目前來說是使用這版本的 感謝

對對對 是指部屬，他就顯示維護（在LINUX上）

**Comment by oniondelta** [comment]
感謝反餽！！！

手頭沒 LINUX 機器，一些 LINUX 使用者發生問題，這邊只能通靈回答XD

會 LAG 需排查：可能是輸入法主程式（例：fcitx-rime）本身問題、或是主程式界面設定問題、或是其安裝套件太舊、或是這邊方案寫法問題。

mixin 方案許多功能實現，所依賴的 librime-lua 外掛套件的維護開發者之一使用的是 ibus-rime，
理論上 ibus-rime 應該沒什麼問題，
但之前建議給使用 LINUX 網友，卻說 ibus 用起來問題多多XD
