### ISSUE TITLE
請問 Mix-in 注音有辦法輸入簡體中文嗎？

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Onion_Rime_Files#24]
今天在 Issues 頁面看到有人問過簡體中文切換失效的問題，不過我去 WIKI 頁面查了一下沒有這功能。

**Comment by oniondelta** [comment]
- https://github.com/oniondelta/Onion_Rime_Files/wiki/%E3%80%94%E6%B4%8B%E8%94%A5%E6%B3%A8%E9%9F%B3%E7%B3%BB%E5%88%97%E3%80%95%EF%BC%9A%E7%B0%A1%E9%AB%94%E8%88%87%E5%AD%97%E7%AC%A6%E7%AF%84%E5%9C%8D
- https://github.com/oniondelta/Onion_Rime_Files/wiki/%E3%80%94%E6%B4%8B%E8%94%A5%E6%B3%A8%E9%9F%B3%E7%B3%BB%E5%88%97%E3%80%95%EF%BC%9A%E5%8A%9F%E8%83%BD%E9%8D%B5%E5%92%8C%E5%BF%AB%E6%8D%B7%E9%8D%B5

**Comment by laichiaheng** [comment]
原來要展開才看到
