### ISSUE TITLE
mix-in 找不到「㺢㹢狓」這個名詞

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Onion_Rime_Files#27]
昨天在進擊的巨人完結篇認識到了「㺢㹢狓」這種動物，但是搜尋他的發音後嘗試打出來，卻找不到這幾個字，求解。
也希望能夠在詞庫中新增這個名詞。

**Comment by oniondelta** [comment]
可加這個詞，但發現一個尷尬的狀況，
「㺢㹢狓」會被[單字範圍](https://github.com/oniondelta/Onion_Rime_Files/wiki/%E3%80%94%E6%B4%8B%E8%94%A5%E6%B3%A8%E9%9F%B3%E7%B3%BB%E5%88%97%E3%80%95%EF%BC%9A%E7%B0%A1%E9%AB%94%E8%88%87%E5%AD%97%E7%AC%A6%E7%AF%84%E5%9C%8D#-%E5%AD%97%E7%AC%A6%E7%AF%84%E5%9C%8D)給精簡，輸入時會找不到，
「contral」+「 ' 」可打開單字範圍

**Comment by oniondelta** [comment]
單個字，較好去選字！避免選字單長長一大串，一堆冷門字！
打「ㄏㄠˉ」，用「control」+「 ' 」和 「control」+「shift」+「 ' 」切換看選單，就知效果！

別人方案也有一樣功能！但多只粗淺區分是否為 CJK 範圍！

當初花了非常非常多的精力時間去摸索測試，
最後多方考量合理的字符範圍為〈萌典有的單字〉、〈Big5E〉、〈Hkscs〉、〈JIS〉 共 20269 個字符
且用了很特別（獨門）設定技巧去實現，目前沒看其他人的方案如此！

「㺢」和「㹢」兩字很多字典都查不到，屬冷門字！！！
