### ISSUE TITLE
請問要怎麼輸入「𰻞」這個字？

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Onion_Rime_Files#29]
最近 YouTube 看到了𰻞𰻞麵的個特別的詞，但是打不出來。

**Comment by oniondelta** [comment]
「[ㄅㄧㄤˊ](https://zh.wiktionary.org/zh-hant/%F0%B0%BB%9E)」該字沒有收錄！該字在辭海等正統字辭典幾乎沒有收錄！
該字 Unicode 編碼在 CJK Unified Ideographs Extension G，
屬於冷門字編碼範圍，雖該字不算冷門！為知名特色小吃，
因冷門字編碼範圍，即使收錄，許多字型也不支持，會無法顯示！故不收錄！！！
如果這邊硬要收錄，會因字型不支援，顯示不出來，又被反應！
