### ISSUE TITLE
請問 mixin 版本要怎麼指定輸入注音文？

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Onion_Rime_Files#30]

**Comment by oniondelta** [comment]
Wiki 中就有說明：[注音文](https://github.com/oniondelta/Onion_Rime_Files/wiki/%E3%80%94%E6%B4%8B%E8%94%A5%E6%B3%A8%E9%9F%B3%E7%B3%BB%E5%88%97%E3%80%95%EF%BC%9A%E6%B3%A8%E9%9F%B3%E6%96%87)

前綴、後綴擇一即可：
前綴：「 ' 」「 ; 」之後輸入皆為注音文。
後綴：「 ' 」「 ; 」「 ' 」前面輸入整句變注音文。

**Comment by laichiaheng** [comment]
這邊我看不懂，我輸入不管 ' 還是 ; 後面打字完全沒出現注音

**Comment by oniondelta** [comment]
> 無法在輸入狀態截圖,所以用拍照的 我輸入`';ddd`

如果沒有打錯「 ' 」「 ; 」鍵位，尤其是第一個〈不是〉鍵盤左上那個「 ` 」鍵！

應該是 librime 核心版本太低了，無法支援這邊 rime 的新功能語法！[相關討論之議題](https://github.com/oniondelta/Onion_Rime_Files/discussions/34)

需置換 [Oct 14, 2024 之後的 librime 核心](https://github.com/rime/librime/releases) ，[librime 1.12.0](https://github.com/rime/librime/releases/tag/1.12.0)之後！

「 ' 」「 ; 」「 v 」可以查看核心 librime 核心版本，如果無法顯示，為缺失 librime-lua 掛件。

fcitx5 rime 之核心 librime 版本應該很低，且預設 librime-lua 缺失，需自行更新版本和安裝掛件！

fcitx5 rime 核心更新不同於 Win 和 Mac，這邊沒用 Linux，故不熟 fcitx5 librime 核心更新置換流程。

特地安裝實測放上網的文件，其該功能並沒有問題！

<img width="215" height="179" alt="Image" src="https://github.com/user-attachments/assets/78b97634-4174-4844-9d6d-a8e30485d7ff" />
