### ISSUE TITLE
請問有類似以前 Windows 那種標點符號表嗎？

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Onion_Rime_Files#32]
因為實在不知道標點符號的鍵位在哪裡，我想要打英翻中名字中間的那個點。

**Comment by laichiaheng** [comment]
Wiki 看到了，［ ' ］= 、

**Comment by oniondelta** [comment]
那個為「間隔號」之前考究過！
間隔號 ：
台灣標準「‧」U+2027
大陸標準「·」
台灣和對岸不一樣！
