### ISSUE TITLE
行列輸入法按「Space」有時候不能上屏

### ISSUE THREAD

**Issue by macthecadillac** [oniondelta/Onion_Rime_Files#33]
如題所示。

問題好像主要影響到具有特別碼的字––這些字如果輸入時不用特別碼而輸入全碼就會出現這樣的情況，但是如果使用特別碼輸入就不會有問題。如果輸入了全碼用家就必須用數字鍵選字上屏。

例如：打 8-7-3⇣「space」應該打出「你」，但是輸入只會停留在preedit階段，而preedit會變成「kjc 」。

另外，重碼字會強逼選字，不選字的話已輸入的字根都會變成英文字母。香草輸入法並不會這樣。例如：輸入8-「space」，在正常情況應該會顯示選字列，然後如果不選字而直接輸入下一個字的字根程式就應該會把「人」字自動上屏。現實情況並不如此。如果不選字而真接輸入下一個字的字根，preedit會變成英文字母。但是如果在第一次按空格鍵後出現選字列的時候再按一次空格鍵就不會出現這個問題。

系統：fcitx5-rime

**Comment by oniondelta** [comment]
> 例如：打 8-7-3⇣「space」應該打出「你」，但是輸入只會停留在preedit階段，而preedit會變成「kjc 」。

應該是 fcitx5-rime 沒有安裝 rime 外掛套件 librime-lua 造成的 bug！
該套件在 Mac 和 Win 上都是安裝檔就直接附上，fcitx5-rime 要另外裝。
測試 librime-lua 有無正常，於行列方案，輸入「`v」，看是否出現以下版本訊息，沒有則缺失！

![截圖 2024-10-14 12 12 50](https://github.com/user-attachments/assets/73b03478-d4e5-4899-aefc-889eba7cc657)

沒有用 fcitx5-rime，之前網友反饋：https://github.com/oniondelta/Onion_Rime_Files/issues/18#issuecomment-1425047037

> 另外，重碼字會強逼選字，不選字的話已輸入的字根都會變成英文字母。香草輸入法並不會這樣。例如：輸入8-「space」，在正常情況應該會顯示選字列，然後如果不選字而直接輸入下一個字的字根程式就應該會把「人」字自動上屏。現實情況並不如此。如果不選字而真接輸入下一個字的字根，preedit會變成英文字母。但是如果在第一次按空格鍵後出現選字列的時候再按一次空格鍵就不會出現這個問題。

以上兩個問題：
第一還是 librime-lua 缺失，沒解決一切白搭。
第二當初仿照香草輸入法上的行列操作被嫌棄XD，說這樣打字節奏不好，所以利用 librime-lua 做了個切換鍵！初始直接上屏！切換可等同香草輸入法，[參看 wiki 說明](https://github.com/oniondelta/Onion_Rime_Files/wiki/%E3%80%8E-%E6%B4%8B%E8%94%A5%E7%89%88-%E8%A1%8C%E5%88%9730-%E3%80%8F%E6%96%B9%E6%A1%88%E8%AA%AA%E6%98%8E)。

![截圖 2024-10-14 12 21 21](https://github.com/user-attachments/assets/7dae5069-bb7c-4e11-ac31-0b2a95615619)

「▫」和「▪」=「空白鍵」

**Comment by macthecadillac** [comment]
謝謝你的回覆。我的系統確是缺了`librime-lua`，裝了以後第一個問題就解決了。

第二個問題我覺得是個bug。我在我的另外一台電腦上有用香草輸入法，而香草輸入法裡對重碼的處理跟這裡的香草輸入行列模式有差別。香草輸入法裡在出現重碼的時候程式確是會在第一次按空白鍵之後先顯示選字列，但是如果用家不選字而繼續輸入，香草會自動把選字列的第一個選項自動上屏而不會把輸入都變成英文字母。這樣其實一點都不會影響打字節奏，而且按空白鍵之後顯示選字列也可以提醒用家重碼的存在。

**Comment by macthecadillac** [comment]
好的謝謝。Take your time.

**Comment by oniondelta** [comment]
今天寫了一堆，盲猜通靈可能的問題，頭有點昏！
之前有人覺得影響打字節奏，香草模式不好！
覺得每個人的要求或理由很衝突，這種衝突不是第一次遇到！有煩感！😞

你要的操作不難，這幾天寫一下，再拋上來！

可以的話，留言提供一下 fcitx5-rime 上怎麼裝 librime-lua，這也不是第一次遇到！
這邊沒有用 Linux 系統！

**Comment by macthecadillac** [comment]
我的`fcitx5-rime`跟`librime-lua`都是系統套件，但是我的系統是滾動的，套件不算很舊。我用的是openSUSE Tumbleweed，安裝指令是`sudo zypper in librime-lua`。`fcitx5-rime`的版本是`5.1.6`，而`librime-lua`的版本是今年三月份的`20ddea9`版。

如果我的中文寫得不清楚，很抱歉。在美國久了，中文都快忘得一乾二淨。電腦詞彙都是邊寫邊從維基百科上找出來的XD

很感謝你花時間回答我的問題。你這個插件是我試過的fcitx插件裡做得跟行列原版最像的。自從Plasma 5以後gcin不能再在Plasma上運行這是我能找到在Linux上最好用的輸入法套件。Thanks for all the hard work.

**Comment by oniondelta** [comment]
已經寫了差不多！細節再尋一尋，明天上傳更新！你再試用看看！

**Comment by oniondelta** [comment]
已修改好了並上傳：[Releases](https://github.com/oniondelta/Onion_Rime_Files/releases)！

1. 「空格」後接 [a-z,./;]，前面直接上屏！如下影片。
2. 初始改成「香草模式」
3. 符號 w [0-9] 後「space」初始也改為和「香草」一樣為翻頁！且可循環翻頁（末底需多費一鍵）

你再下載來試用看看哪邊有問體！這邊再作修正！

https://github.com/user-attachments/assets/82ce2ad7-be7c-47c7-aeac-cd793fcdabaa

**Comment by macthecadillac** [comment]
一個字根或兩個字根的重碼字現在跟香草一模一樣了，謝謝。但是如果輸入需要三個字根或以上的現在就是在「香草」模式也是直上而沒有在按「空格」之後顯示選字列。例字：劣／沒／汲 (clb)，麯／䴵… (zkkfi)

我用的是macOS版的鼠鬚管測試

**Comment by oniondelta** [comment]
不知道 Windows 上預設的行列 30 操作是怎麼樣？

當初是以「直上」為出發點製作，如同：[線上行列](https://array30.misterfishup.com/)

這個牽涉到這邊特有「標注」（如下圖）和新增功能「詞庫」上屏相關操作。考慮的東西變多！

![截圖 2024-10-14 12 21 21](https://github.com/user-attachments/assets/7dae5069-bb7c-4e11-ac31-0b2a95615619)

**Comment by oniondelta** [comment]
Actions 有修改告一段落的！
上面貼文可能隨時紀錄並改變，較真起來很多細節和設置衝突！

**Comment by macthecadillac** [comment]
我下載了新版本試了一下，用上來挺順手的。謝謝。

> 「詞庫」上屏相關操作。如「單字」或「詞條」等多種情形下有重碼！「空格」後細節怎麼操作！如下圖例子！怎麼操作？直接把詞庫設成只有尾綴「'」才顯示？還是詞庫同「單字」？承上，這樣「詞庫」是否要切成二碼以下不加空格和三碼以上加空格兩部分？真正官方詞庫是怎麼上屏的？

我沒用過官方的行列，只用過Windows內置的版本和行列小站上的「新行列30輸入法」。Windows內置版跟「香草」一樣都是只有聯想字而不帶官方所描述的詞庫功能的，而「新行列30」也可能是有這個功能的，但是我沒有試過在打字的時候尾綴「'」，所以真的是不知道到底有沒有這個功能。按照行列官方的描述，在輸入時是需要輸入「'」才會顯示詞條的。這樣可以大幅減低重碼率。我覺得我們可以新增一個用戶設定，讓用家可以自行選擇是否只有尾綴「'」才顯示詞條選項。

官方有關詞彙輸入描述的網頁：https://www.array.com.tw/class/class2.htm

> 這邊打字有「選字單」並操作「方向鍵」後，「空格」設成直接上屏選項，「香草」那邊直接設成不能用「方向鍵」XD
這和你要的「space」功能有矛盾！例：輸入「jj」後，移動了「方向鍵」，又想打「jj空格」出「再」！目前這邊需要補個「tab」回復才可！
且要像「香草」行列30的「space」翻頁又上屏，還另需有別於「直上」作分別設置。
這邊是不打算像「香草」一樣廢棄用「方向鍵」！
這邊不習慣「香草」一點，為「space」有時為「翻頁鍵」，有時為「上屏」，輸入「zkkfi」，按「空白」後，再按「空白」為翻頁，「kkk」則為上屏，不一致導致不習慣。
是否拔掉「return」輸出英文功能，轉成強制直接上屏所選候選字，「space」就為一般「space」或不變？只是這對依賴「return」輸出英文功能的人，變為「shift+return」輸出，接受度如何？
還是如何設置較合理呢？

我從來沒有試過在選字單操作方向鍵，所以對此沒甚麼意見。據我記憶在Windows內置的行列也是不讓用家在選字列操作方向鍵的。「新行列30」也是一樣。值得一提的是「香草」除了在符號表用空格鍵翻頁，只會在選字表裡有超過10個候選字的時候用空格鍵翻頁。以我所知「新行列30」也是一樣的操作，而Windows內置的行列輸入法因為不是大字集的緣故，我找不到重碼有超過10個候選字的輸入字元組，所以無從考究。

至於用「Enter/Return」輸入英文，這無論是在「香草」或Windows內置的行列或是「新行列30」都是不容許的。Windows內置版的操作跟「香草」略有不同。Windows內置的行列在用戶打「Enter」的時候會先清除preedit然後當成一般按「Enter」處理，而在「香草」在顯示選字單的時候會不理會「return」鍵。我覺得如果用家選擇用香草模式，我們可以合理地假設他們曾經用過「香草」並了解「香草」的基本操作。他們應該也不會想到要用「Enter/return」輸入英文吧。

> 承上「space」操作問題，如符號 w[a-z,./;] 時仿香草「space」操作為「翻頁」，和一般輸入選字時的「上屏」作用不同，感覺不很融合？！

我用了行列十多年，不管是「香草」、「DIME」、「gcin」、「ibus array」、或是「新行列30」的操作一直都是這個樣子的。可能是習慣了，不怎麼覺得有問題。

**Comment by macthecadillac** [comment]
承上，細閱行列官方對詞彙輸入的描述後理解官方版的行列會只有在輸入「'」的時候會輸出詞彙，而如果用戶輸入空白鍵官版行列就只會輸出單字。如果輸入錯誤後按空白鍵即便字元串可當成詞彙也不會意外地輸入詞彙。

**Comment by oniondelta** [comment]
1. 只在最後輸入「'」才會輸出詞彙，這樣在設定上比較好處理。但當初想說「減少輸入鍵數」，且可提前看到可能有的詞條，結果在你這邊變成了：「如果輸入錯誤後按空白鍵即便字元串可當成詞彙也不會意外地輸入詞彙。⚠️」，感覺變成了一個 bug ！弄這個很心累的原因在這，不是說沒道理，每網友的切入點（習慣點）都不同！很多網友一開口這邊傻眼，一堆設定衝突和視為怎樣設定為理所當然，把設定者或其他網友考慮的東西視為不需要考慮XD。

2. 「return」鍵輸出「英文」在 rime 這邊，很多其他形碼都刻意增設這個設定！即便在該形碼原版上沒有！方便，很多人喜歡，之前看過幾個方案被要求加入！但感覺你那邊要完全復刻「官版」或「香草」！以那個為依歸！這邊很不喜歡「香草」的「space」「return」「方向鍵」設定，或許其他版本的行列也是這樣設定，這邊在斟酌，你那邊則視為理所當然。

3. 
 > 承上「space」操作問題，如符號 w[a-z,./;] 時仿香草「space」操作為「翻頁」，和一般輸入選字時的「上屏」作用不同，感覺不很融合？！

這邊是在說「space」操作不一致的問題，不是你的習慣！「space」在符號 w[a-z,./;] 時設定「翻頁」，但一般輸入「space」設定不是「翻頁」，是說這個不一致感！要嘛全部設成「翻頁」，還是回到你想復刻你的習慣問題！

4.
 > 「香草」作為主打字型輸入法的輸入法框架，專案作者大概也沒有想到有用方向鍵移動游標的需要吧。

一堆形碼都會用到方向鍵去翻頁或選字單上選字！

**Comment by macthecadillac** [comment]
> 只在最後輸入「'」才會輸出詞彙，這樣在設定上比較好處理。但當初以「減少輸入鍵數」為出發，且可提前看到可能有的詞條，特意的多費工的設置，結果在你這邊變成了：「如果輸入錯誤後按空白鍵即便字元串可當成詞彙也不會意外地輸入詞彙。⚠️」，感覺變成了一個 bug ！弄這個很心累的原因在這，不是說沒道理，每網友的切入點（習慣點）都不同！很多網友一開口這邊傻眼，一堆設定衝突，和視為理所當然、理應如此的想法，把設定者或其他網友考慮的東西視為不需要考慮XD。

> 這個是「較少鍵數輸入詞條」和「單字和詞條分開處理」兩者的抉擇！只是被說成像 bug 一樣，傻眼！

我沒有把這一點當成bug。只不過是討論一下而已。

> 「return」鍵輸出「英文」在 rime 這邊，很多其他形碼都刻意增設這個設定！即便在該形碼原版上沒有！方便，很多人喜歡，之前看過幾個別人的形碼方案，被要求加入！但感覺你那邊要完全復刻「官版」或「香草」！以那個為依歸！這邊不喜歡「香草」的「space」「return」「方向鍵」設定，或許其他版本的行列也是這樣設定，這邊在斟酌，你那邊視為理所當然。

> 目前抉擇是〔return〕:「直接上屏所選字」或「上屏英文」，這邊不要「香草」那種〔return〕，很多時候沒作用。

這我理解，對此我也沒有意見，畢竟這對我的打字習慣完全沒有影響。我是見到你的討論之後花了幾個小時去研究了一下其它專案的做法，回來給你彙報一下。完全沒有把甚麼視為理所當然的。

我沒有想要跟你爭論。我覺得現在的版本也已經夠好了。你覺得下一步應該怎麼做你可以自己做決定。我不再說了。少說少錯。

**Comment by oniondelta** [comment]
> 我是見到你的討論之後花了幾個小時去研究了一下其它專案的做法，回來給你彙報一下。完全沒有把甚麼視為理所當然的。

這也沒要爭論，只是想說出自己的感受！

上面這就是糾結的問題！有時不知道該不該感謝大家花時間的使用和指教 XD
我這花的修改和研究時間更多！不只有你的想法和觀點的實現！拜託理解！🙏🏻‍
但是感覺很多網友認為花時間用我的方案，是對我這邊的利益！
更何況像你願意花時間來研究！而我花的時間和考慮無所謂！

還是很感謝你花了幾個小時去研究，但也請理解我所花的時間和考慮！才會講那麼多！

留言有修改，看一下吧！初心只是提供方案設置技巧！

**Comment by oniondelta** [comment]
你覺得吃力不討好！
我也覺得吃力不討好！

大家這是在幹嘛XD！
