### ISSUE TITLE
請問如何記住常用詞？

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Onion_Rime_Files#6]
請問輸入法本身是否不會記住常用詞？因為有些詞每次都要選字，要怎麼新增或者是修改呢？

想要再請教一下有辦法直接更改後方的字嗎？選字每次都要從最前頭開始選。

**Comment by oniondelta** [comment]
一般都會記住常用詞，
有時記不住
在 Mac 使用 fn+shift+delete 刪除前方不要選項的用戶詞典記憶即可！
（其他系統：Shift+Delete 或 Control+Delete）

字碼順序包含
  - essay-zh-hant-onion.txt（八股文檔）
和以下一眾字詞典
  - terra_pinyin_onion
  - terra_pinyin_onion_add
  - bo_mixin_jp
  - bo_mixin_kr
  - bo_mixin_la
  - phrases.cht_en_w
  - phrases.chtp
  - phrases.jp_hk_more
  - phrases.jp_hkkreduce
  - phrases.kr_more
  - phrases.en_o_w
  - phrases.la_py_w
  - phrases.en_l_w
  - phrases.en_u_w
請自行研究，反正就修改或加個詞頻
八股文檔是基底，字詞典的詞頻是變化
䰖兒	zuan3 er5	80%
す	!!su	70000
