### ISSUE TITLE
請問 mix-in 如何輸入宇多田 hi ka ru 呢？

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Onion_Rime_Files#7]
不好意思，想要照您的範例輸入宇多田 hikaru 都失敗，完全沒看到片假名

**Comment by oniondelta** [comment]
先選「宇多田」再選「ヒカル」
記憶後就可直接打

ㄩˇㄉㄨㄛˉㄊㄧㄢˊhi.ka.ru.
輸入「.」次尾綴調出片假名
輸入「,」次尾綴調出平假名

更限定的調用可再加尾綴
mix-in 裡面包含四種尾綴調出的方案
（尾綴：調出不同語言）
（次尾綴：同一語言但大小寫或平片假名不同的區分）

如："☆注音(洋蔥mix-in版 4 )☆〔全 ˊ ˇ ˋ ˙ 〕"該版「空格」為外語尾綴
ㄩˇㄉㄨㄛˉㄊㄧㄢˊhi.空ka.空ru.空
（「空」為空白鍵）

如："☆注音(洋蔥mix-in版 1 )☆〔拉日 ˇ  ˋ 韓〕"該版「6」為日語尾綴
ㄩˇㄉㄨㄛˉㄊㄧㄢˊhi.6ka.6ru.6

**Comment by laichiaheng** [comment]
瞭解，不過分那麼多版本好像有點複雜

**Comment by oniondelta** [comment]
覺得複雜就不要用呀！！！

各個細分版本都是這邊辛苦寫出來的！
各個細分版本有各個優缺點！
說明書之前在部落格有寫！後來拿掉不提供了！

方案寫得單一精簡，意見一堆！
分多個版本提供選擇，又說太複雜，真難搞！

**Comment by laichiaheng** [comment]
@oniondelta 就是因為沒有說明書才整個很複雜呀！畢竟分那麼多版本，但是又不曉得他們之間差別在哪裡

**Comment by laichiaheng** [comment]
@oniondelta 請問他有辦法將日文平假名切換成漢字嗎？譬如「べんとう」變成「弁当」
