### ISSUE TITLE
在 Qbittorrent 從注音模式切換到英文模式後，輸入英文加上數字後方會多出現亂碼

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Onion_Rime_Files#9]
```
OS：ArchLinux
DE：Gnome41 Wayland
發生軟體：Qbittorrent
```

**重現步驟**
1. 在輸入框內輸入注音但不要按下 Enter。
2. Backspace 清除注音。
3. 切換到英文模式。
4. 輸入英文並按下 Enter。

**結果**
如下圖所示，後方多出了一個注音。
![2022-02-20 15-03-58 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/154832295-5f8524ac-ad15-4be8-a6bd-a4bea3144065.png)
如上圖所示，結尾會多出空格和注音

**Comment by oniondelta** [comment]
早前 Mac 上的 Excel 也會發生此情形，
後來 Excel 更新版後，就沒發生此情形！
早前  Mac 上 Chrome 某些地方連系統輸入法輸入都有問題，
後來更了好幾版後，才終於沒問題！

這類問題，請先測試：
1. 其他軟體使用該方案是否有此類問題？
2. Rime 官方的方案是否有此類問題？
3. 原生系統輸入法是否有此類問題？

通靈不好通！
這邊只作方案，Rime 主程式或使用軟體的問題，愛莫能助！

**Comment by laichiaheng** [comment]
@oniondelta 在 LibreOffice Calc 測試後同樣也會發生，嘗試用日文沒有出現同樣狀況
![2022-02-21 23-39-18 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/154986719-d4263c5e-11ca-4040-9eb2-6d106dd67fc7.png)

**Comment by oniondelta** [comment]
親測 Mac 上的 LibreOffice Calc 沒問題！
通靈：
日文in1 中的 preedit_format 沒轉寫，
純注音或 mix-in 轉寫成ㄅㄆㄇㄈ，
可能是造成的原因？？？
官方注音方案有測試嗎？
如果也是這樣，十之八九就是 preedit_format 無法被軟體適應，
沒有  preedit_format 無法顯示你按的注音為何，只能顯示 abcd，
故這邊無解！

**Comment by laichiaheng** [comment]
@oniondelta 套用 Windows 的方法成功了！
官方注音方案要測試只能夠刪掉 RIME 重新安裝嗎？因為不曉得怎麼切回官方的注音輸入法。

**Comment by oniondelta** [comment]
看來 Linux 上 ibus-rime 也無法吃 \n 該程式碼！

可不用重新安裝，於 default.custom.yaml 增加以下其中一行：
```
    - schema: cangjie5
    - schema: bopomofo
    - schema: bopomofo_tw
```
第一個為官方倉頡、後兩個為官方注音！都有參考性！

問一下， ibus-rime 下 mix-in 版按「'」「/」「f」有出現日期嗎？
依網友反映，發現 fcitxi-rime 核心好像很舊，無法使用 mix-in 版的外掛 lua。
好似連純注音中有使用到 Rime 較新的程式碼，都無法作用？雖然還是可以打字。

**Comment by laichiaheng** [comment]
@oniondelta 
沒看到有日期

**Comment by oniondelta** [comment]
那表示  ibus-rime 官方封裝不支援 lua（ Mac 和 Win 親測都支援）
這樣用 mix-in 和 plus 方案會產生一些 bug 和功能缺失！
不止不能輸入日期！

2019年時說不支援，現在也…
以下幾篇好似有解法，不熟 ibus-rime 也沒機器，你自己慢慢搞吧！

https://github.com/hchunhui/librime-lua/issues/22
https://github.com/hchunhui/ibus-rime.AppImage
https://github.com/rime/ibus-rime/issues/123

**Comment by laichiaheng** [comment]
𝟐𝟔
